    spring.application.name=app



    spring.datasource.url=jdbc:postgresql://localhost:5432/civa_buses_db
    spring.datasource.username=postgres
    spring.datasource.password=root
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=create
    spring.jpa.properties.hibernate.format_sql=true
    jwt.secret=miClaveSecretaSuperSeguraDeAlMenos64CaracteresParaHS512Funcione!!
    jwt.expiration=600000