    spring.application.name=app



    spring.datasource.url=jdbc:postgresql://localhost:5432/civa_buses_db
    spring.datasource.username=postgres
    spring.datasource.password=root
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=create
    spring.jpa.properties.hibernate.format_sql=false
    jwt.secret=miClaveSecretaSuperSeguraDeAlMenos64CaracteresParaHS512Funcione!!
    jwt.expiration=600000



    logging.level.root=INFO
    logging.level.com.gestion.buses=DEBUG
    logging.level.org.springframework=INFO

    logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) $cyan(%logger{36})  - %msg%n